# Generated by Django 2.2.7 on 2019-12-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191203_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Classification'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='provider',
            field=models.ManyToManyField(blank=True, to='movies.Provider'),
        ),
    ]
