# Generated by Django 2.2.7 on 2019-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191203_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_providers',
            field=models.ManyToManyField(blank=True, to='movies.Provider'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
