# Generated by Django 2.2.7 on 2019-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191204_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
