# Generated by Django 2.2.7 on 2019-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20191204_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
