# Generated by Django 2.2.7 on 2019-12-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20191205_2244'),
        ('movies', '0003_auto_20191204_2012'),
    ]

    operations = [
    ]
