# Generated by Django 2.2.7 on 2019-12-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_merge_20191207_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieId',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='no-img.png', upload_to=''),
        ),
    ]
